# Generated by Django 4.1.6 on 2023-02-04 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chesswar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='boardno',
            field=models.IntegerField(default=0, verbose_name='Board Number'),
        ),
        migrations.AlterField(
            model_name='board',
            name='busy',
            field=models.BooleanField(default=False, verbose_name='Match Live On Board?'),
        ),
        migrations.AlterField(
            model_name='board',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Board Location'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='BoardWinner', to='chesswar.registration', verbose_name='Board Winner'),
        ),
    ]
