# Generated by Django 4.1.6 on 2023-02-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chesswar', '0002_alter_board_boardno_alter_board_busy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='over',
            field=models.BooleanField(default=False, verbose_name='Duel Over?'),
        ),
    ]
