# Generated by Django 4.1.6 on 2023-02-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chesswar', '0003_duel_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
