# Generated by Django 5.0.2 on 2024-02-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chesswar', '0004_alter_annoucements_warning_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='times_white_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Participant Email'),
        ),
    ]
